Cleari/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from apps.services.pwa.views import pub_verify
from apps.services.pwa.views import sw, index

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', index, name='index'),
                  path('pwa/', include('apps.services.pwa.urls', namespace='pwa_service')),
                  path('basic/', include('apps.services.basic.urls', namespace='basic_service')),
                  path('sw.js', sw, name='service_worker'),
                  # Public Clearance Verification
                  path('pub/verify/<str:code>', pub_verify, name='public_clearance_verification'),
                  url(r'^webpush/', include('webpush.urls')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/modules/message/urls.py
from django.urls import path
from django.views.decorators.http import require_POST

from . import pwa_views

app_name = 'message'

urlpatterns = [
    path('inbox/', pwa_views.Inbox.as_view(), name='inbox'),
    path('new/', pwa_views.NewMessage.as_view(), name='new_message'),
    path('m/<str:msg_id>', pwa_views.Chat.as_view(), name='chat'),
    path('deleted/<str:msg_id>/<str:pk>', pwa_views.DeleteMessage.as_view(), name='delete'),
    path('reply/<str:msg_id>', require_POST(pwa_views.Reply.as_view()), name='reply'),
]

templates/core/home.html
{% load indexer %}
{% load humanize %}
{% block title %}{{ data.title.name }}{% endblock %}

{% block content %}
    {% if request.user.is_authenticated %}
        <h3>Account:</h3>
        <p>Hi, <b>{{ request.user.first_name }}</b></p>
        {% if user.type == 'signatory' %}
            <ul>
                <li>Dashboard</li>
                <ul>
                    <li><a href="{% url 'liability:add' %}" title="Add Liability">Add Liability</a></li>
                    <li><a href="{% url 'receipt:issue_receipt' %}" title="Issue Liability">Issue Liability</a></li>
                </ul>
            </ul>
        {% endif %}
        <ul>
            <li><b>Settings</b>
                <ul>
                    {% if user.type == 'signatory' %}
                        <li><a href="{% url 'core:set_signature' %}" title="Setup Signature">Setup Signature</a></li>
                    {% endif %}
                    <li><a href="{% url 'core:set_email' %}" title="Setup Email">Configure Email</a></li>
                    <li><a href="{% url 'core:edit_profile' %}" title="Edit Profile">Edit Profile</a></li>
                    <li><a href="{% url 'core:change_password' %}" title="Change Password">Change Password</a></li>
                </ul>
            </li>
            <li><b>Messages</b>
                <ul>
                    <li><a href="{% url 'message:inbox' %}" title="View Inbox">Inbox</a></li>
                    <li><a href="{% url 'message:new_message' %}" title="New Message">New Message</a></li>
                </ul>
            </li>
        </ul>
        <p><b><a href="{% url 'core:logout' %}" title="logout">Logout</a></b></p>
    {% endif %}
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    {% if data.error %}
        <div style="align-content: center; width: 100%">
            <b>Boo!</b>

            <p>{{ data.message }}</p>
        </div>
    {% else %}
        <hr>
        <p><b>Semester:</b>{{ schoolsem.semester.current|ordinal }}</p>
        <select name="sys" onchange="location = this.value;">
            <option value="#">Select Semester</option>
            {% for val in schoolsem.semester.list %}
                <option value="{% url 'core:select_semester' sy=val.school_year sem=val.semester %}">
                    S.Y.20{{ val.school_year|split_start:2 }}-20{{ val.school_year|split_end:2 }} {{ val.semester|ordinal }}
                    Semester
                </option>
            {% endfor %}
        </select>
        <p><b>School Year & Semester:</b> {{ data }}</p>
        <p><b>Clearance Start:</b>{{ clearance.start }}</p>
        <p><b>Clearance End</b>{{ clearance.end }}</p>
        <!-- TODO: Clearance Duration is Live -->
        {% if clearance.valid %}
            <p><b>Clearance Duration:</b> {{ clearance.duration }}</p>
        {% else %}
            <p><b>Clearance Duration:</b> Clearance is already Closed!</p>
        {% endif %}
        <hr>
        {% if user.type == 'student' %}
            <p><b>Name:</b>{{ user.name }}</p>
            <p><b>ID Number:</b>{{ user.id_number }}</p>
            <p><b>Course:</b>{{ user.course }}</p>
            <p><b>College:</b>{{ user.college }}</p>
            <p>Violations: <b>{{ user.has_violation }}</b></p>
            <p>Violation Details: <b>{% for v in user.violations %}
                {{ v.reason }}
            {% endfor %}</b></p>
            <p>
            <form method="get" action="{% url 'core:search' %}">
                {{ search.as_p }}
                <button type="submit">Search</button>
            </form>
            </p>
            <hr>
            {% if user.has_liabilities %}
                <p><i>Liabilities</i></p>
                <ul>
                    {% for lbts in user.liabilities %}
                        <li>{{ lbts.liability|split_dex:1 }} -
                            {% if lbts.is_cleared %}
                                {% if lbts.receipt|validate_receipt %}
                                    Signed
                                {% else %}
                                    Not Signed
                                {% endif %}
                            {% else %}
                                Not Signed
                            {% endif %}
                            - {{ lbts.liability.signatory.office }}
                            {% if lbts.is_requested %}
                                {% if clearance.valid %}
                                    {% if lbts.is_cleared %}
                                        <b>Request Received</b>
                                    {% else %}
                                        <b>Request Sent</b>
                                    {% endif %}
                                {% else %}
                                    <b>Request Sent</b>-<p>Please follow up on respected signatory</p>
                                {% endif %}
                            {% else %}
                                {% if clearance.valid %}
                                    <a href="{% url 'student:request_approval' liability_id=lbts.liability.liability office=lbts.liability.signatory.office %}">Request</a>
                                {% else %}
                                    <b>Request Restricted</b>
                                {% endif %}
                            {% endif %}
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <p><i>You have no liabilities Yet.</i></p>
            {% endif %}
        {% elif user.type == 'signatory' %}
            <p><b>Signatory Name:</b>{{ user.name }}</p>
            <p><b>ID Number:</b>{{ user.id_number }}</p>
            <p><b>College:</b>{{ user.college }}</p>
            <p><b>Office:</b>{{ user.office }}</p>
            <p><b>Position:</b>{{ user.position }}</p>
            {% if user.assigned %}
                <form method="get" action="{% url 'signatory:search_students' %}">
                    {{ search_form.as_p }}
                    <button type="submit">Search</button>
                </form>
                <p>Students that are no liabilities</p>
                <ul>
                    {% if clients.fresh.exists %}
                        {% for f in clients.fresh %}
                            <li>{{ f.number }} - {{ f.first_name }} - {{ f.last_name }} - No Liability Issued</li>
                        {% endfor %}
                    {% else %}
                        <li>Not New Students</li>
                    {% endif %}
                </ul>
                <p>Students issued liabilities</p>
                <ul>
                    {% if clients.issued.exists %}
                        {% for f in clients.issued %}
                            <li>{{ f.number }} - {{ f.first_name }} - {{ f.last_name }} -
                                {% for l1 in f.receipt_set.all %}{{ l1.receipt }}{% endfor %}</li>
                        {% endfor %}
                    {% else %}
                        <li>No Students Issued Yet</li>
                    {% endif %}
                </ul>
                <p>Students Request to be Signed</p>
                <ul>
                    {% if clients.requesting.exists %}
                        {% for f in clients.requesting %}
                            <li>{{ f.number }} - {{ f.first_name }} - {{ f.last_name }} -
                                {% for l1 in f.receipt_set.all %}
                                    {{ l1.receipt }} - {{ l1.amount }} - {{ l1.is_requested }} -
                                    <a href="{% url 'receipt:sign_receipt' receipt=l1.receipt %}">Sign</a>
                                {% endfor %}
                            </li>
                        {% endfor %}
                    {% else %}
                        <li>No Students are Requesting</li>
                    {% endif %}
                </ul>
                <p>Students Signed</p>
                <ul>
                    {% if clients.signed.exists %}
                        {% for f in clients.signed %}
                            <li>{{ f.number }} - {{ f.first_name }} - {{ f.last_name }} -
                                {% for l1 in f.receipt_set.all %}{{ l1.receipt }} - {{ l1.amount }} -{{ l1.is_cleared }}
                                    - {% if l1.receipt|validate_receipt %} Valid Signature - {% else %}
                                    Invalid Signature {% endif %}{% endfor %}</li>
                        {% endfor %}
                    {% else %}
                        <li>No Students are Signed</li>
                    {% endif %}
                </ul>
            {% else %}
                <p>Your account is not assigned to any clearance</p>
            {% endif %}
        {% else %}
        {% endif %}
    {% endif %}
{% endblock %}

templates/core/index.html
{% extends 'base.html' %}
{% block title %} Home {% endblock %}
{% block content %}
    <b> Welcome to Cleari </b>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    {% if request.user.is_authenticated %}
        <p><a href="{% url 'core:home' %}" title="Home">Home</a></p>
    {% else %}
        <p><a href="{% url 'core:login' %}" title="Login">Login</a></p>
    {% endif %}
    <p>This is a temporary page for Cleari.</p>
    <i>{{ data }}</i>
{% endblock %}

templates/core/manage.html
{% extends 'base.html' %}
{% block title %}{{ app.title }}{% endblock %}
{% block content %}
    <a href="{% url 'core:home' %}" title="Home">Home</a>
    <hr>
    <h3>Manage {{ app.name }} </h3>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <ul>
        <li>Dashboard</li>
        <ul>
            {% for l in links %}
                <li><a href="{{ l.url }}" title="{{ l.title }}">{{ l.text }}</a></li>
            {% endfor %}
        </ul>
    </ul>
{% endblock %}